### ISSUE TITLE
Any plans for Folder Support

### ISSUE THREAD

**Issue by adenau** [f100024/syncthing_exporter#2]
Hi,

Great job with the exporter. I was wondering if you had any plans to add support for folders, so we could see which folders are not up to sync and by how much.

Meanwhile, I created a fork with a Dockerfile, I'm happy to contribute a pull request if you are interested.

Cheers,

**Comment by f100024** [comment]
Hi @adenau,

> Great job with the exporter. I was wondering if you had any plans to add support for folders, so we could see which folders are not up to sync and by how much.

Thanks. You mean this api endpoint https://docs.syncthing.net/rest/stats-folder-get.html ?

> Meanwhile, I created a fork with a Dockerfile, I'm happy to contribute a pull request if you are interested.

Sure, let's try. :)

**Comment by blockloop** [comment]
@f100024 I think @adenau is talking about [db-need](https://docs.syncthing.net/rest/db-need-get.html) which tells us how many
files are needed to be in sync. This is something I have been wanting to
monitor so that I can tell when my machines are out of sync. I also think "last
seen" for each device would be useful to monitor [from here](https://docs.syncthing.net/rest/stats-device-get.html).

**Comment by f100024** [comment]
@adenau @blockloop hi, I've added folder support in version `0.3.0` you can already test it. Also have been added last seen for device [from here](https://docs.syncthing.net/rest/stats-device-get.html). I close this issue if you have any sugetstions please create new.
